OP-264 Added fixes and updates to the plugin
BitBagCommerce/SyliusInPostPlugin pull request #25
Opened 2024-05-10 12:38 UTC by SzymonKostrubiec

+ Fixed bug with FlashbagInterface
+ Added form validator for phone number with phpSpec tests
+ Update Readme

2024-05-22 10:41 UTC, SzymonKostrubiec commented on src/Resources/translations/validators.en.yml
> +        phone_number:
No, we don't have polish translations in this plugin

2024-05-22 18:40 UTC, senghe requested changes

2024-05-22 18:40 UTC, senghe commented on src/Validator/HasValidPhoneNumberInPostOrderValidator.php
> +        }
`Assert::instanceOf($value, OrderInterface::class);`

2024-05-22 18:40 UTC, senghe commented on src/Validator/HasValidPhoneNumberInPostOrderValidator.php
> +            throw new \Exception('Value must be instance of InPostPointsAwareInterface');
Similar as above

2024-05-24 10:38 UTC, senghe approved these changes

2024-06-03 19:46 UTC, senghe requested changes

2024-06-03 19:46 UTC, senghe commented on src/Validator/HasValidPhoneNumberInPostOrderValidator.php
> +    private function formatPhoneNumber($phone): string
Missing parameter type

2024-06-03 19:46 UTC, senghe commented on src/Validator/Constraint/HasValidPhoneNumberInPostOrder.php
> +    public const POSSIBLE_POLISH_PHONE_PREFIXES = [
I wouldn't call it with POLISH. It's just POSSIBLE_PHONE_PREFIXES.

2024-06-03 19:46 UTC, senghe commented on src/Resources/translations/validators.en.yml
> +            incorrect_length: "Incorrect phone number for Polish shipping methods"
Phone number must consist of 9 digits.

2024-06-03 19:46 UTC, senghe commented on src/Validator/Constraint/HasValidPhoneNumberInPostOrder.php
>      public const POLISH_PHONE_NUMBER_DEFAULT_LENGTH = 9;
Please remove the POLISH :pray:

2024-06-05 06:11 UTC, senghe approved these changes

2024-06-17 19:36 UTC, merged